name: CI build-and-push-docker-image

on:
  workflow_run:
    workflows: ["CI test-backend"]
    types: 
      - completed
    branches: 
      - main

jobs:
  # ----------------------------------------
  # 3. BUILD AND PUSH BACKEND DOCKER IMAGE
  # ----------------------------------------
  build-and-push-backend:
    name: Push Backend Image
    # Ensures this only runs if the tests actually succeeded (not if they failed or were cancelled)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./Backend API/simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: true

  # ----------------------------------------
  # 4. BUILD AND PUSH DATABASE DOCKER IMAGE
  # ----------------------------------------
  build-and-push-database:
    name: Push Database Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./Database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
          push: true

  # ----------------------------------------
  # 5. BUILD AND PUSH HTTPD DOCKER IMAGE
  # ----------------------------------------
  build-and-push-httpd:
    name: Push HTTPD Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
          push: true
