name: CI devops 2025

on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  # ----------------------------------------
  # 1. TEST JOB
  # ----------------------------------------
  test-backend: 
    name: Test Backend Code
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        working-directory: "Backend API/simple-api"
        run: ./mvnw clean verify

  # ----------------------------------------
  # 2. SONARCLOUD QUALITY GATE JOB
  # ----------------------------------------
  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        working-directory: "Backend API/simple-api"
        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=Harish-Arvind_GitHub-Actions -Dsonar.organization=harish-arvind -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  # ----------------------------------------
  # 3. BUILD AND PUSH BACKEND DOCKER IMAGE
  # ----------------------------------------
  build-and-push-backend:
    name: Push Backend Image
    needs: [test-backend, sonar-analysis]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./Backend API/simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

  # ----------------------------------------
  # 4. BUILD AND PUSH DATABASE DOCKER IMAGE
  # ----------------------------------------
  build-and-push-database:
    name: Push Database Image
    needs: [test-backend, sonar-analysis]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./Database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

  # ----------------------------------------
  # 5. BUILD AND PUSH HTTPD DOCKER IMAGE
  # ----------------------------------------
  build-and-push-httpd:
    name: Push HTTPD Image
    needs: [test-backend, sonar-analysis]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
